### ISSUE TITLE
How come the question is deleted?

### ISSUE THREAD

**Issue by jlian2** [astro-zihao/mucko#3]
We concern that there is no json file available so that we can not reproduce this paper. But why did you delete our questions?

**Comment by jlian2** [comment]
We would make a report to IJCAI if this is deleted again.

**Comment by astro-zihao** [comment]
> We would make a report to IJCAI if this is deleted again.

You can email to me and I will send you the download link.

**Comment by astro-zihao** [comment]
> We concern that there is no json file available so that we can not reproduce this paper. But why did you delete our questions?

We have no intention of releasing the data. If you would like to have access to the data, please email to me and I will send you the download link.

**Comment by guoyang9** [comment]
Hi Zihao @astro-zihao , could you also share me with the additional data? I already sent you two consecutive emails a week ago but haven't received any response yet. I suppose it's because of the network delay?
